AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless assigment-2
Parameters:
  ApiGatewayStageName:
    Type: String
    Default: Dev
    Description: The name of the stage for the API Gateway
Resources:
  ApiGatewayAssigment2:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiGatewayStageName
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: "No Proxy Integration Example"
          version: 1.0
        x-amazon-apigateway-request-validators:
          ValidateBody:
            validateRequestBody: true
            validateRequestParameters: false
        paths:
          /:
            post:
              x-amazon-apigateway-request-validator: ValidateBody
              responses:
                "200":
                  Description: "Successful operation"
                  content:
                    application/json:
                      schema:
                        type: object
                "500":
                  Description: "Internal Server Error"
              x-amazon-apigateway-integration:
                type: aws
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionAssigment2.Arn}/invocations"
                httpMethod: POST
                passthroughBehaviour: "WHEN_NO_TEMPLATES"
                requestTemplates:
                  application/json: |
                    {
                      "body": $input.json('$'),
                      "extraField": "12345"
                    }
                responses:
                  default:
                    statusCode: 200


  LambdaFunctionAssigment2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/main.handler
      Runtime: nodejs20.x
      FunctionName: assigemnt2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref ApiGatewayAssigment2

          