AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless assigment-2
Parameters:
  ApiGatewayStageName:
    Type: String
    Default: Dev
    Description: The name of the stage for the API Gateway
Resources:
  ApiGatewayAssigment2:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiGatewayStageName

  LambdaFunctionAssigment2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/main.handler
      Runtime: nodejs20.x
      FunctionName: assigemnt2
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30